export default {
    en: {
        delete: 'Delete',
        loading: 'Loading',
        increment: 'Increment',
        user: 'User',
        userName: 'User Name',
        comment: 'Comment',
        commentsShow: 'Show Comments',
        commentsHide: 'Hide Comments',
        newArticleForm: 'New Article form',
        language: 'Current language: ',
        counter: 'Counter',
        filters: 'Filters',
        articles: 'Articles',
        comments: 'Comments',
        nocomments: 'No comments yet',
        reset: 'Reset',
        pleaseSelectArticle: 'Please select an article',
        selectfirstday: 'Please select the first day.',
        changelanguage: "Change language"
    },

    ru: {
        delete: 'Удалить',
        loading: 'Загрузка',
        increment: 'Увеличить',
        user: 'Пользователь',
        userName: 'Имя пользователя',
        comment: 'Комментарий',
        commentsShow: 'Показать комментарии',
        commentsHide: 'Спрятать комментарии',
        newArticleForm: 'Новая статья',
        language: 'Текущий язык: ',
        counter: 'Счетчик',
        filters: 'Фильтры',
        articles: 'Статьи',
        comments: 'Комментарии',
        nocomments: 'Нет комментариев',
        reset: 'Сбросить',
        pleaseselectarticle: 'Пожайлуйста, выберите статью',
        selectfirstday: 'Пожалуйста, выберите дату',
        changelanguage: 'Изменить язык'
    }
}